import { db, storage } from "./firebase.js";
import { requireVerifiedUser, ensureUserDoc, logout } from "./auth.js";
import { seasons, teams } from "./seed-data.js";
import { collection,getDocs,doc,setDoc,getDoc,serverTimestamp,query,orderBy,updateDoc,addDoc } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import { ref, getBlob } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
const $=id=>document.getElementById(id);const user=await requireVerifiedUser({admin:true});await ensureUserDoc(user);$("adminEmail").textContent=user.email;$("logoutBtn").onclick=logout;
for(const b of document.querySelectorAll('[data-panel]'))b.onclick=()=>{document.querySelectorAll('[data-panel]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.admin-panel').forEach(x=>x.classList.remove('active'));$(b.dataset.panel).classList.add('active')};
await Promise.all([loadAthletes(),loadRegistrations(),loadPayments(),loadDocuments(),loadTeams()]);

$("seedBtn").onclick=async()=>{if(!confirm('Initialize / refresh the 2026–27 season and team catalog?'))return;for(const s of seasons)await setDoc(doc(db,'seasons',s.id),{...s,updatedAt:serverTimestamp()},{merge:true});for(const t of teams)await setDoc(doc(db,'teams',t.id),{...t,updatedAt:serverTimestamp()},{merge:true});toast('Catalog initialized.','success');await loadTeams()};

let athletes=[];async function loadAthletes(){const snap=await getDocs(collection(db,'athletes'));athletes=snap.docs.map(d=>({uid:d.id,...d.data()}));$("athleteCount").textContent=athletes.length;renderAthletes()}
function renderAthletes(){const q=$("athleteSearch").value.toLowerCase();const rows=athletes.filter(a=>`${a.firstName||''} ${a.lastName||''} ${a.grade||''} ${a.guardianName||''}`.toLowerCase().includes(q));$("athleteRows").innerHTML=rows.map(a=>`<tr><td><strong>${esc(a.firstName)} ${esc(a.lastName)}</strong><br><small>${esc(a.email||'')}</small></td><td>${esc(a.grade||'')}</td><td>${esc(a.gender||'')}</td><td>${esc(a.guardianName||'')}</td><td>${esc(a.guardianPhone||'')}</td><td><button class="btn btn-secondary" data-open-athlete="${a.uid}">Open</button></td></tr>`).join('')||'<tr><td colspan="6">No athletes yet.</td></tr>';document.querySelectorAll('[data-open-athlete]').forEach(b=>b.onclick=()=>openAthlete(b.dataset.openAthlete))}$("athleteSearch").oninput=renderAthletes;
async function openAthlete(uid){const a=athletes.find(x=>x.uid===uid);$("selectedAthlete").textContent=`${a.firstName||''} ${a.lastName||''}`;$("selectedAthleteUid").value=uid;document.querySelector('[data-panel="athletesPanel"]').click();$("athleteDetail").innerHTML=`<div class="grid grid-3"><div><span class="metric-label">Grade</span><div class="metric">${esc(a.grade||'—')}</div></div><div><span class="metric-label">Guardian</span><p>${esc(a.guardianName||'—')}<br>${esc(a.guardianPhone||'')}</p></div><div><span class="metric-label">Emergency</span><p>${esc(a.emergencyName||'—')}<br>${esc(a.emergencyPhone||'')}</p></div></div>`}

async function loadRegistrations(){let all=[];for(const a of athletes){const snap=await getDocs(collection(db,'athletes',a.uid,'registrations'));snap.forEach(d=>all.push({id:d.id,uid:a.uid,athlete:`${a.firstName||''} ${a.lastName||''}`,...d.data()}))}$("registrationCount").textContent=all.length;$("registrationRows").innerHTML=all.map(r=>`<tr><td>${esc(r.athlete)}</td><td>${esc(r.teamName||r.teamId)}</td><td>${esc(r.league||'')}</td><td><span class="badge badge-blue">${esc(r.status||'submitted')}</span></td></tr>`).join('')||'<tr><td colspan="4">No registrations yet.</td></tr>'}

async function loadPayments(){let rows=[];for(const a of athletes){const snap=await getDocs(collection(db,'athletes',a.uid,'payments'));snap.forEach(d=>rows.push({id:d.id,uid:a.uid,athlete:`${a.firstName||''} ${a.lastName||''}`,...d.data()}))}let due=0,paid=0;rows.forEach(p=>{due+=Number(p.amountDue||0);paid+=Number(p.amountPaid||0)});$("paymentsDue").textContent=money(Math.max(0,due-paid));$("paymentsPaid").textContent=money(paid);$("paymentRows").innerHTML=rows.map(p=>`<tr><td>${esc(p.athlete)}</td><td>${esc(p.label||'Sports fee')}</td><td>${money(p.amountDue)}</td><td>${money(p.amountPaid)}</td><td>${esc(p.status||'due')}</td></tr>`).join('')||'<tr><td colspan="5">No fees posted.</td></tr>'}
$("feeForm").onsubmit=async e=>{e.preventDefault();const uid=$("feeAthleteUid").value.trim();if(!uid)return;await addDoc(collection(db,'athletes',uid,'payments'),{label:$("feeLabel").value,amountDue:Number($("feeDue").value||0),amountPaid:Number($("feePaid").value||0),status:$("feeStatus").value,method:$("feeMethod").value,reference:$("feeReference").value,updatedAt:serverTimestamp()});e.target.reset();toast('Fee record saved.','success');await loadPayments()};

async function loadDocuments(){let rows=[];for(const a of athletes){const snap=await getDocs(collection(db,'athletes',a.uid,'documents'));snap.forEach(d=>rows.push({id:d.id,uid:a.uid,athlete:`${a.firstName||''} ${a.lastName||''}`,...d.data()}))}$("documentPending").textContent=rows.filter(r=>(r.reviewStatus||'pending')==='pending').length;$("documentRows").innerHTML=rows.map(r=>`<tr><td>${esc(r.athlete)}</td><td>${esc(r.type)}</td><td><button class="btn btn-secondary" data-open-file="${escAttr(r.storagePath||'')}">Open Securely</button></td><td>${esc(r.reviewStatus||'pending')}</td><td><button class="btn btn-secondary" data-doc="${r.uid}|${r.id}|approved">Approve</button> <button class="btn btn-danger" data-doc="${r.uid}|${r.id}|rejected">Reject</button></td></tr>`).join('')||'<tr><td colspan="5">No documents uploaded.</td></tr>';document.querySelectorAll('[data-open-file]').forEach(b=>b.onclick=async()=>{try{const blob=await getBlob(ref(storage,b.dataset.openFile));const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(err){toast('Unable to open this protected file.','danger')}});document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=async()=>{const [uid,id,status]=b.dataset.doc.split('|');await updateDoc(doc(db,'athletes',uid,'documents',id),{reviewStatus:status,reviewedAt:serverTimestamp(),reviewedBy:user.email});toast(`Document ${status}.`,'success');await loadDocuments()})}

async function loadTeams(){const snap=await getDocs(collection(db,'teams'));const catalog=snap.empty?teams:snap.docs.map(d=>({id:d.id,...d.data()}));$("teamCount").textContent=catalog.length;$("teamRows").innerHTML=catalog.map(t=>`<tr><td><strong>${esc(t.name)}</strong></td><td>${esc(t.league)}</td><td>${esc(t.grades)}</td><td>${esc(t.seasonId)}</td><td>${money(t.costEstimate||0)}</td><td>${esc(t.status||'')}</td></tr>`).join('')}
function toast(text,type='info'){const e=$("adminStatus");e.textContent=text;e.className=`notice ${type} status show`;setTimeout(()=>e.classList.remove('show'),5000)}function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escAttr(v){return esc(v)}
