import { db, storage } from "./firebase.js";
import { requireVerifiedUser, ensureUserDoc, logout } from "./auth.js";
import { doc,getDoc,setDoc,collection,getDocs,addDoc,serverTimestamp,query,orderBy } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import { ref,uploadBytes } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
import { teams } from "./seed-data.js";
const $=id=>document.getElementById(id); let user,profile={};
user=await requireVerifiedUser(); await ensureUserDoc(user); $("userEmail").textContent=user.email; $("logoutBtn").onclick=logout;
await loadProfile(); await loadRegistrations(); await loadPayments(); await loadDocuments();

async function loadProfile(){const snap=await getDoc(doc(db,'athletes',user.uid));profile=snap.exists()?snap.data():{};if(profile.firstName){$("welcomeName").textContent=profile.firstName;$("profileComplete").classList.add('hidden')}else{$("profileComplete").classList.remove('hidden')}const ids=['firstName','lastName','dob','grade','gender','phone','guardianName','guardianEmail','guardianPhone','emergencyName','emergencyPhone','shirtSize','medicalNotes'];ids.forEach(id=>{if($(id))$(id).value=profile[id]||''});updateCompletion()}
$("profileForm").addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());data.updatedAt=serverTimestamp();data.email=user.email;await setDoc(doc(db,'athletes',user.uid),data,{merge:true});profile={...profile,...data};flash('profileStatus','Profile saved.','success');updateCompletion()});

function updateCompletion(){const keys=['firstName','lastName','dob','grade','gender','guardianName','guardianPhone','emergencyName','emergencyPhone'];const pct=Math.round(keys.filter(k=>profile[k]).length/keys.length*100);$("profilePct").textContent=pct+'%';$("profileBar").style.width=pct+'%'}

async function loadRegistrations(){const target=$("registrationList");const snap=await getDocs(collection(db,'athletes',user.uid,'registrations'));const existing=snap.docs.map(d=>({id:d.id,...d.data()}));target.innerHTML=existing.length?existing.map(r=>`<div class="check"><span>🏅</span><div><strong>${r.teamName||r.teamId}</strong><small>${r.status||'Submitted'} • ${r.seasonName||''}</small></div></div>`).join(''):'<p>No registrations submitted yet.</p>';const sel=$("teamSelect");sel.innerHTML='<option value="">Choose a team</option>'+teams.map(t=>`<option value="${t.id}">${t.name} • ${t.grades} • ${t.league}</option>`).join('')}
$("registrationForm").addEventListener('submit',async e=>{e.preventDefault();if(!profile.firstName){flash('registrationStatus','Complete the athlete profile before registering.','warning');return;}const team=teams.find(t=>t.id===$("teamSelect").value);if(!team)return;await addDoc(collection(db,'athletes',user.uid,'registrations'),{teamId:team.id,teamName:team.name,seasonId:team.seasonId,league:team.league,status:'submitted',submittedAt:serverTimestamp(),athleteUid:user.uid});flash('registrationStatus','Interest / registration submitted.','success');e.target.reset();await loadRegistrations()});

async function loadPayments(){const snap=await getDocs(collection(db,'athletes',user.uid,'payments'));let due=0,paid=0;const rows=snap.docs.map(d=>d.data());rows.forEach(p=>{due+=Number(p.amountDue||0);paid+=Number(p.amountPaid||0)});$("amountDue").textContent=money(Math.max(0,due-paid));$("paymentRows").innerHTML=rows.length?rows.map(p=>`<tr><td>${p.label||'Sports fee'}</td><td>${money(p.amountDue||0)}</td><td>${money(p.amountPaid||0)}</td><td><span class="badge ${p.status==='paid'?'badge-green':'badge-gold'}">${p.status||'due'}</span></td></tr>`).join(''):'<tr><td colspan="4">No sports fees posted.</td></tr>'}

async function loadDocuments(){const snap=await getDocs(collection(db,'athletes',user.uid,'documents'));const docs=snap.docs.map(d=>d.data());$("docList").innerHTML=docs.length?docs.map(d=>`<div class="doc-row"><div><strong>${labelDoc(d.type)}</strong><small style="display:block;color:var(--muted)">${d.fileName||''}</small></div><span class="badge ${d.reviewStatus==='approved'?'badge-green':d.reviewStatus==='rejected'?'badge-red':'badge-gold'}">${d.reviewStatus||'pending'}</span></div>`).join(''):'<p>No documents uploaded yet.</p>'}
$("uploadForm").addEventListener('submit',async e=>{e.preventDefault();const type=$("docType").value,file=$("docFile").files[0];if(!type||!file)return;if(file.size>10*1024*1024){flash('uploadStatus','Maximum file size is 10 MB.','warning');return;}const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`athlete-documents/${user.uid}/${type}/${Date.now()}-${safe}`;const sref=ref(storage,path);flash('uploadStatus','Uploading…','info');await uploadBytes(sref,file,{contentType:file.type});await addDoc(collection(db,'athletes',user.uid,'documents'),{type,fileName:file.name,storagePath:path,reviewStatus:'pending',uploadedAt:serverTimestamp()});e.target.reset();flash('uploadStatus','Document uploaded securely.','success');await loadDocuments()});

function labelDoc(t){return ({birth_certificate:'Birth Certificate',physical:'Sports Physical',insurance:'Insurance Card',other:'Other Document'})[t]||t}function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))}function flash(id,text,type){const el=$(id);el.textContent=text;el.className=`notice ${type} status show`;setTimeout(()=>el.classList.remove('show'),5000)}
