import { db,storage } from "./firebase.js";
import { requireVerifiedUser,ensureUserDoc,logout } from "./auth.js";
import { teams as fallbackTeams,seasons as fallbackSeasons,seasonMap as fallbackSeasonMap } from "./seed-data.js";
import { collection,getDocs,addDoc,doc,getDoc,setDoc,serverTimestamp,query,where } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import { ref,uploadBytes } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js";
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const user=await requireVerifiedUser(); await ensureUserDoc(user); $('userEmail').textContent=user.email; $('logoutBtn').onclick=logout;
let athletes=[],current=null,teams=fallbackTeams,seasons=fallbackSeasons,seasonMap=fallbackSeasonMap,docs=[],payments=[],regs=[];
await loadCatalog(); await loadFamily();
async function loadCatalog(){try{const [ts,ss]=await Promise.all([getDocs(collection(db,'teams')),getDocs(collection(db,'seasons'))]);if(!ts.empty)teams=ts.docs.map(d=>({id:d.id,...d.data()}));if(!ss.empty)seasons=ss.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.order||0)-(b.order||0));seasonMap=Object.fromEntries(seasons.map(s=>[s.id,s]));}catch(e){}}
async function loadFamily(){const snap=await getDocs(query(collection(db,'athletes'),where('familyUid','==',user.uid)));athletes=snap.docs.map(d=>({id:d.id,...d.data()}));renderAthleteCards();if(current){const fresh=athletes.find(a=>a.id===current.id);if(fresh)await selectAthlete(fresh.id);} }
function renderAthleteCards(){$('athleteCards').innerHTML=athletes.length?athletes.map(a=>`<button class="card athlete-card ${current?.id===a.id?'selected':''}" data-athlete="${a.id}"><span class="metric-label">Grade ${esc(a.grade||'—')}</span><h3>${esc(name(a))}</h3><p>${esc(a.gender||'')}</p></button>`).join(''):'<div class="card"><h3>No athletes yet</h3><p>Add your first athlete to begin.</p></div>';document.querySelectorAll('[data-athlete]').forEach(b=>b.onclick=()=>selectAthlete(b.dataset.athlete));}
$('addAthleteBtn').onclick=()=>$('addAthleteModal').classList.remove('hidden');$('cancelAddAthlete').onclick=()=>$('addAthleteModal').classList.add('hidden');
$('addAthleteForm').onsubmit=async e=>{e.preventDefault();const ref=await addDoc(collection(db,'athletes'),{familyUid:user.uid,firstName:$('newFirst').value.trim(),lastName:$('newLast').value.trim(),grade:Number($('newGrade').value),gender:$('newGender').value,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});$('addAthleteModal').classList.add('hidden');e.target.reset();await loadFamily();await selectAthlete(ref.id);};
async function selectAthlete(id){current=athletes.find(a=>a.id===id);if(!current)return;$('athleteWorkspace').classList.remove('hidden');$('profileHeading').textContent=`${name(current)} Profile`;for(const k of ['firstName','lastName','dob','grade','gender','phone','guardianName','guardianEmail','guardianPhone','emergencyName','emergencyPhone','shirtSize','medicalNotes'])$(k).value=current[k]??'';$('eligibilityStatus').textContent=current.adminEligibility==='ineligible'?'Ineligible':current.adminEligibility==='hold'?'On Hold':'Eligible';renderAthleteCards();updateProfilePct();await Promise.all([loadDocs(),loadPayments(),loadRegs()]);await loadSchedule();renderSeasonSelect();}
$('profileForm').onsubmit=async e=>{e.preventDefault();const data={};for(const k of ['firstName','lastName','dob','grade','gender','phone','guardianName','guardianEmail','guardianPhone','emergencyName','emergencyPhone','shirtSize','medicalNotes'])data[k]=$(k).value.trim?.()??$(k).value;data.grade=Number(data.grade);data.updatedAt=serverTimestamp();await setDoc(doc(db,'athletes',current.id),data,{merge:true});flash('profileStatus','Profile saved.','success');await loadFamily();};
function updateProfilePct(){const keys=['firstName','lastName','dob','grade','gender','guardianName','guardianPhone','emergencyName','emergencyPhone'];const pct=Math.round(keys.filter(k=>current[k]).length/keys.length*100);$('profilePct').textContent=pct+'%';$('profileBar').style.width=pct+'%';}
function publicEligible(t){const g=Number(current.grade||0);return g>=Number(t.publicMinGrade??99)&&g<=Number(t.publicMaxGrade??-1)&&(t.allowedGender==='Coed'||t.allowedGender===current.gender)&&!['cancelled','complete'].includes(t.status);}
function renderSeasonSelect(){$('registrationSeason').innerHTML='<option value="">Choose season</option>'+seasons.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');$('registrationSeason').onchange=renderChoices;renderChoices();}
function renderChoices(){const sid=$('registrationSeason').value;const eligible=teams.filter(t=>t.seasonId===sid&&publicEligible(t));const opts='<option value="">None</option>'+eligible.map(t=>`<option value="${t.id}">${esc(t.name)} • ${esc(t.league)} • ${esc(t.grades)}</option>`).join('');$('firstChoice').innerHTML=opts.replace('>None<','>Choose first choice<');$('secondChoice').innerHTML=opts;}
$('registrationForm').onsubmit=async e=>{e.preventDefault();if(!current)return;const seasonId=$('registrationSeason').value,first=$('firstChoice').value,second=$('secondChoice').value;if(!seasonId||!first)return flash('registrationStatus','Choose a season and first choice.','warning');if(first===second&&second)return flash('registrationStatus','First and second choice must differ.','warning');const ref=doc(db,'athletes',current.id,'seasonRegistrations',seasonId);if((await getDoc(ref)).exists())return flash('registrationStatus','Season choices already exist. Contact Athletics to change them.','warning');await setDoc(ref,{athleteId:current.id,familyUid:user.uid,seasonId,firstChoice:first,secondChoice:second,firstStatus:'submitted',secondStatus:second?'submitted':'',notes:$('registrationNotes').value.trim(),submittedAt:serverTimestamp(),updatedAt:serverTimestamp()});flash('registrationStatus','Season choices submitted.','success');e.target.reset();await loadRegs();};
async function loadRegs(){const snap=await getDocs(collection(db,'athletes',current.id,'seasonRegistrations'));regs=snap.docs.map(d=>({seasonId:d.id,...d.data()}));$('registrationList').innerHTML=regs.length?regs.map(r=>`<div class="check"><div><strong>${esc(seasonMap[r.seasonId]?.name||r.seasonId)}</strong><small>1st: ${esc(teamName(r.firstChoice))} • ${esc(r.firstStatus)}${r.secondChoice?`<br>2nd: ${esc(teamName(r.secondChoice))} • ${esc(r.secondStatus)}`:''}</small></div></div>`).join(''):'<p>No season registrations yet.</p>';}
$('docType').onchange=()=> $('physicalDates').classList.toggle('hidden',$('docType').value!=='physical');
$('uploadForm').onsubmit=async e=>{e.preventDefault();const type=$('docType').value,file=$('docFile').files[0];if(!type||!file)return;if(file.size>=10*1024*1024)return flash('uploadStatus','File must be under 10 MB.','danger');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`athlete-documents/${user.uid}/${current.id}/${type}/${Date.now()}-${safe}`;await uploadBytes(ref(storage,path),file,{contentType:file.type});await addDoc(collection(db,'athletes',current.id,'documents'),{type,fileName:file.name,storagePath:path,reviewStatus:'pending',physicalExamDate:type==='physical'?$('physicalExamDate').value:'',physicalExpirationDate:type==='physical'?$('physicalExpirationDate').value:'',uploadedAt:serverTimestamp()});e.target.reset();$('physicalDates').classList.add('hidden');flash('uploadStatus','Uploaded securely for review.','success');await loadDocs();};
async function loadDocs(){const snap=await getDocs(collection(db,'athletes',current.id,'documents'));docs=snap.docs.map(d=>({id:d.id,...d.data()}));const approved=new Set(docs.filter(d=>d.reviewStatus==='approved'&&!docExpired(d)).map(d=>d.type));$('docMetric').textContent=`${['birth-certificate','physical'].filter(x=>approved.has(x)).length}/2`;$('docList').innerHTML=docs.length?docs.map(d=>`<div class="doc-row"><div><strong>${esc(docLabel(d.type))}</strong><small style="display:block">${esc(d.fileName||'')}${d.type==='physical'&&d.physicalExpirationDate?` • expires ${esc(d.physicalExpirationDate)}`:''}</small></div><span class="badge ${d.reviewStatus==='approved'&&!docExpired(d)?'badge-green':d.reviewStatus==='rejected'?'badge-red':'badge-gold'}">${docExpired(d)?'expired':esc(d.reviewStatus||'pending')}</span></div>`).join(''):'<p>No documents uploaded.</p>';}
async function loadPayments(){const snap=await getDocs(collection(db,'athletes',current.id,'payments'));payments=snap.docs.map(d=>({id:d.id,...d.data()}));const bal=payments.reduce((n,p)=>n+Math.max(0,Number(p.amountDue||0)-Number(p.amountPaid||0)),0);$('amountDue').textContent=money(bal);$('paymentRows').innerHTML=payments.length?payments.map(p=>`<tr><td>${esc(p.label||'Sports Fee')}</td><td>${money(p.amountDue)}</td><td>${money(p.amountPaid)}</td><td>${money(Math.max(0,Number(p.amountDue||0)-Number(p.amountPaid||0)))}</td><td>${esc(p.status||'due')}</td></tr>`).join(''):'<tr><td colspan="5">No fees posted.</td></tr>';}
async function loadSchedule(){const approved=[];for(const r of regs){if(r.firstStatus==='approved')approved.push(r.firstChoice);if(r.secondStatus==='approved'&&r.secondChoice)approved.push(r.secondChoice);}let ev=[];for(const tid of approved){const s=await getDocs(collection(db,'teams',tid,'events'));s.forEach(d=>ev.push({teamId:tid,...d.data()}));}ev.sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`));$('athleteEventList').innerHTML=ev.length?ev.map(e=>`<div class="check"><div><strong>${esc(e.date||'')} • ${esc(e.title||'')}</strong><small>${esc(teamName(e.teamId))} • ${esc(e.start||'')} ${e.arrivalTime?`• Arrive ${esc(e.arrivalTime)}`:''} ${e.location?`• ${esc(e.location)}`:''}</small></div></div>`).join(''):'<p>No approved-team events yet.</p>';}
function docExpired(d){return d.type==='physical'&&d.physicalExpirationDate&&d.physicalExpirationDate<new Date().toISOString().slice(0,10)} function docLabel(x){return x==='birth-certificate'?'Birth Certificate':x==='physical'?'Sports Physical':'Insurance'} function teamName(id){return teams.find(t=>t.id===id)?.name||id} function name(a){return `${a.firstName||''} ${a.lastName||''}`.trim()||'Unnamed Athlete'} function flash(id,text,type){const el=$(id);el.textContent=text;el.className=`notice ${type} status show`;setTimeout(()=>el.classList.remove('show'),5000)} function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))}
