export const seasons = [
  {id:"s1-fall",name:"Season 1 • Fall",order:1,start:"2026-08-03",end:"2026-11-19",status:"active",note:"CAA elementary volleyball begins earlier; confirmed IYAC Season 1 competition is Sept. 21–Nov. 19."},
  {id:"s2-late-fall",name:"Season 2 • Late Fall",order:2,start:"2026-09-21",end:"2026-12-19",status:"planned",note:"CAA Boys Volleyball and Girls Flag Football overlap the end of IYAC Season 1."},
  {id:"s3-winter",name:"Season 3 • Winter",order:3,start:"2026-11-16",end:"2027-03-10",status:"planned",note:"IYAC basketball is historically Dec–Feb; CAA Boys Flag runs Jan–Mar."},
  {id:"s4-spring",name:"Season 4 • Spring",order:4,start:"2027-02-15",end:"2027-05-15",status:"planned",note:"IYAC soccer historically Mar–May; CAA spring offerings overlap."}
];

export const teams = [
  {id:"s1-caa-girls-vb-45",seasonId:"s1-fall",name:"Girls Volleyball",sport:"Volleyball",league:"CAA",grades:"4–5",gender:"Girls",publicMinGrade:4,publicMaxGrade:5,adminMinGrade:4,adminMaxGrade:5,allowedGender:"Girl",costEstimate:1000,status:"active",placement:"Elementary-first",minRoster:8,targetRoster:10,sportsFee:100},
  {id:"s1-iyac-girls-vb-ms",seasonId:"s1-fall",name:"MS Girls Volleyball",sport:"Volleyball",league:"IYAC",grades:"6–8",gender:"Girls",publicMinGrade:6,publicMaxGrade:8,adminMinGrade:5,adminMaxGrade:8,allowedGender:"Girl",costEstimate:0,status:"planned",placement:"IYAC-first; 5th only by admin exception",minRoster:8,targetRoster:10,sportsFee:0},
  {id:"s1-iyac-coed-flag-ms",seasonId:"s1-fall",name:"MS Coed Flag Football",sport:"Flag Football",league:"IYAC",grades:"6–8",gender:"Coed",publicMinGrade:6,publicMaxGrade:8,adminMinGrade:5,adminMaxGrade:8,allowedGender:"Coed",costEstimate:0,status:"planned",placement:"IYAC-first; 5th only by admin exception",minRoster:8,targetRoster:12,sportsFee:0},
  {id:"s2-caa-boys-vb-46",seasonId:"s2-late-fall",name:"Boys Volleyball",sport:"Volleyball",league:"CAA",grades:"4–6",gender:"Boys",publicMinGrade:4,publicMaxGrade:6,adminMinGrade:4,adminMaxGrade:6,allowedGender:"Boy",costEstimate:1000,status:"interest",placement:"6th is a bridge grade",minRoster:8,targetRoster:10,sportsFee:100},
  {id:"s2-caa-girls-flag-46",seasonId:"s2-late-fall",name:"Girls Flag Football",sport:"Flag Football",league:"CAA",grades:"4–6",gender:"Girls",publicMinGrade:4,publicMaxGrade:6,adminMinGrade:4,adminMaxGrade:6,allowedGender:"Girl",costEstimate:1000,status:"interest",placement:"Elementary-first; 6th used as bridge when appropriate",minRoster:8,targetRoster:12,sportsFee:100},
  {id:"s2-internal-esports",seasonId:"s2-late-fall",name:"Esports",sport:"Esports",league:"Internal",grades:"4–8",gender:"Coed",publicMinGrade:4,publicMaxGrade:8,adminMinGrade:4,adminMaxGrade:8,allowedGender:"Coed",costEstimate:0,status:"interest",placement:"Mario Kart + Smash Bros are one program",minRoster:4,targetRoster:10,sportsFee:0},
  {id:"s2-internal-chess",seasonId:"s2-late-fall",name:"Chess",sport:"Chess",league:"Internal",grades:"4–8",gender:"Coed",publicMinGrade:4,publicMaxGrade:8,adminMinGrade:4,adminMaxGrade:8,allowedGender:"Coed",costEstimate:0,status:"interest",placement:"Internal",minRoster:4,targetRoster:10,sportsFee:0},
  {id:"s3-iyac-boys-bball",seasonId:"s3-winter",name:"MS Boys Basketball",sport:"Basketball",league:"IYAC",grades:"6–8",gender:"Boys",publicMinGrade:6,publicMaxGrade:8,adminMinGrade:5,adminMaxGrade:8,allowedGender:"Boy",costEstimate:0,status:"planned",placement:"IYAC-first; 5th only by admin exception",minRoster:8,targetRoster:10,sportsFee:0},
  {id:"s3-iyac-girls-bball",seasonId:"s3-winter",name:"MS Girls Basketball",sport:"Basketball",league:"IYAC",grades:"6–8",gender:"Girls",publicMinGrade:6,publicMaxGrade:8,adminMinGrade:5,adminMaxGrade:8,allowedGender:"Girl",costEstimate:0,status:"planned",placement:"IYAC-first; 5th only by admin exception",minRoster:8,targetRoster:10,sportsFee:0},
  {id:"s3-caa-girls-bball-45",seasonId:"s3-winter",name:"Girls Basketball",sport:"Basketball",league:"CAA",grades:"4–5",gender:"Girls",publicMinGrade:4,publicMaxGrade:5,adminMinGrade:4,adminMaxGrade:5,allowedGender:"Girl",costEstimate:1000,status:"viability",placement:"Participation dependent",minRoster:8,targetRoster:10,sportsFee:100},
  {id:"s3-caa-boys-flag-45",seasonId:"s3-winter",name:"Boys Flag Football",sport:"Flag Football",league:"CAA",grades:"4–5",gender:"Boys",publicMinGrade:4,publicMaxGrade:5,adminMinGrade:4,adminMaxGrade:5,allowedGender:"Boy",costEstimate:1000,status:"planned",placement:"Elementary-first",minRoster:8,targetRoster:12,sportsFee:100},
  {id:"s4-iyac-coed-soccer",seasonId:"s4-spring",name:"MS Coed Soccer",sport:"Soccer",league:"IYAC",grades:"6–8",gender:"Coed",publicMinGrade:6,publicMaxGrade:8,adminMinGrade:5,adminMaxGrade:8,allowedGender:"Coed",costEstimate:0,status:"planned",placement:"IYAC-first; 5th only by admin exception",minRoster:9,targetRoster:14,sportsFee:0},
  {id:"s4-caa-boys-bball-45",seasonId:"s4-spring",name:"Boys Basketball",sport:"Basketball",league:"CAA",grades:"4–5",gender:"Boys",publicMinGrade:4,publicMaxGrade:5,adminMinGrade:4,adminMaxGrade:5,allowedGender:"Boy",costEstimate:1000,status:"planned",placement:"Elementary-first",minRoster:8,targetRoster:10,sportsFee:100},
  {id:"s4-caa-coed-soccer-45",seasonId:"s4-spring",name:"Coed Soccer",sport:"Soccer",league:"CAA",grades:"4–5",gender:"Coed",publicMinGrade:4,publicMaxGrade:5,adminMinGrade:4,adminMaxGrade:5,allowedGender:"Coed",costEstimate:1000,status:"viability",placement:"Only if participation supports cost",minRoster:9,targetRoster:14,sportsFee:100}
];
export const seasonMap=Object.fromEntries(seasons.map(s=>[s.id,s]));
export const teamMap=Object.fromEntries(teams.map(t=>[t.id,t]));
